# Generated by Django 5.2.4 on 2025-07-09 17:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_fill_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to='map.zone')),
            ],
        ),
    ]
